
name: 📚 Documentation Issue
description: Request additions or improvements to the documentation
labels: "documentation"
body:
  - type: markdown
    attributes:
      value: |
        > 🚨 If you have encountered a SECURITY RELATED ISSUE with Yii, [use this form](https://www.yiiframework.com/security) to report any security issues you have encountered to us. ***WARNING!*** DO NOT use the issue tracker or discuss it in the public forum as this will cause more harm than help.
  - type: textarea
    id: id-issue-category
    attributes:
      label: Issue Category
      description: Choose the options that best describe your suggestion. **Delete what does not apply.**
      value: |
        - Typo or editorial suggestion (**Link to page:**)
        - Incorrect/Outdated information (**Link to page:**)
        - Missing page/section/topic (**Link to page:**)
        - Can't find an answer to a specific question ✔️
        - Organization/Navigation suggestion ✔️
        - Other ✔️

    validations:
      required: true
  - type: textarea
    id: id-description
    attributes:
      label: Description
      description: |
        Describe what you expected to find. Also include relevant motivation and context.
        If applicable, you can attach images by clicking this area to highlight it and then dragging files in.
        :warning: _Remember to redact or remove any sensitive information!_
      placeholder: Please put specific details about the typo, error, missing info, suggestion, etc here.
    validations:
      required: true