name: Bug Report
literal_block: |
  > If you have encountered a security-related issue with Yii, please use the [security issue form](https://www.yiiframework.com/security) to report any security issues you have encountered to us.
  > ###<span style="color:red;">Warning</span>
  > <span style="color:red;">***DO NOT use the issue tracker or discuss it in the public forum as it will cause more damage than help.***</span>

description: Create a bug report
labels: ["defect"]
body:
  - type: dropdown
    id: yiiversion
    attributes:
      label: Yii Version
      description: Which version of Yii are you using?
      placeholder: "2.0.49 (latest)"
      multiple: false
      options:
        - 2.0.49 (latest)
        - 2.0.48
        - 2.0.47
        - 2.0.46
        - 2.0.45
        - 2.0.44
        - 2.0.43
        - 2.0.42
        - 2.0.41
        - 2.0.40
        - 2.0.39
        - 2.0.38
        - 2.0.37
        - 2.0.36
        - 2.0.35
        - 2.0.34
        - 2.0.33
        - 2.0.32
        - 2.0.31
        - 2.0.30
        - 2.0.29
        - 2.0.28
        - 2.0.27
        - 2.0.26
        - 2.0.25
        - 2.0.24
        - 2.0.23
        - 2.0.22
        - 2.0.21
        - 2.0.20
        - 2.0.19
        - 2.0.18
        - 2.0.17
        - 2.0.16
        - 2.0.15
        - 2.0.14
        - 2.0.13
        - 2.0.12
        - 2.0.11
        - 2.0.10
        - 2.0.9
        - 2.0.8
        - 2.0.7
        - 2.0.6
        - 2.0.5
        - 2.0.4
        - 2.0.3
        - 2.0.2
        - 2.0.1
        - 2.0.0
        - 1
      default: 0
    validations:
      required: true
  - type: dropdown
    id: phpversion
    attributes:
      label: Version PHP
      description: What version of PHP are you running?
      placeholder: "8.0 (Default)"
      multiple: false
      options:
        - 7.4
        - 8.0 (Default)
        - 8.1
        - 8.2
        - 8.3
      default: 1
    validations:
      required: true
  - type: dropdown
    id: osversion
    attributes:
      label: Operating System
      description: What version of operating system are you running?
      placeholder: "Microsoft Windows (Default)"
      multiple: false
      options:
        - Microsoft Windows (Default)
        - Apple macOS
        - Linux
        - Android
        - iOS
        - Chrome OS
      default: 0
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: What is the expected result?
      placeholder: Describe what you expected to happen
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description and a way to reproduce the problem.
      placeholder: Please use the [Yii Chat channel](https://t.me/yii3en), [IRC channel](ircs://irc.libera.chat:6697/yii) or [Yii Forum](https://forum.yiiframework.com/c/yii-3-0/63) for questions.
    validations:
      required: true

Remember_block: |
  > Remember, contributions to this repository should follow its <a style="text-decoration: underline" class="Link--inTextBlock" href="https://github.com/yiisoft/docs?tab=coc-ov-file#">contributing guidelines</a> and <a style="text-decoration: underline" styleclass="Link--inTextBlock" href="https://github.com/yiisoft/docs?tab=security-ov-file#">security policy</a>.
