
name: 🐞 Report an issue
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        > 🚨 If you have encountered a SECURITY RELATED ISSUE with Yii, [use this form](https://www.yiiframework.com/security) to report any security issues you have encountered to us. ***WARNING!*** DO NOT use the issue tracker or discuss it in the public forum as this will cause more harm than help.
  - type: textarea
    id: id-expected
    attributes:
      label: What is the expected result?
      placeholder: |
        Describe what you expected to happen.
        Please also include relevant motivation and context. 
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 'Is there an existing issue for this?'
      description: 'Please [search :mag: the issues](https://github.com/appium/appium/issues) to check if this bug has already been reported.'
      options:
      - label: 'I have searched the existing issues'
        required: true
  - type: input
    id: id-fix-issues
    attributes:
      label: "Fixes # (issue)"
      description: Please enter comma-separated list of tickets, if any
      placeholder: 'ex. #1234; #45678; #99990;'
    validations:
      required: false
  - type: textarea
    id: id-description
    attributes:
      label: "Description"
      description: |
        Description of your incident. Please use the [Yii Chat channel](https://t.me/yii3en) or [Yii Forum](https://forum.yiiframework.com/c/yii-3-0/63) for questions.
      placeholder: Write in detail anything that gives us more context about the problem you are facing!
    validations:
      required: true
  - type: input
    id: id-reprod-url
    attributes:
      label: "Reproduction URL"
      description: Please enter your GitHub URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: false
  - type: textarea
    id: id-reprod
    attributes:
      label: "Reproduction steps"
      description: |
        Please enter an explicit description of your issue.
        Reproductions cases must be minimal and focused around the specific problem you are experiencing. This is the best way to ensure this issue is triaged quickly.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: id-screenshot-logs
    attributes:
      label: "Screenshots / Logs"
      description: |
        If applicable, you can attach images or log files by clicking this area to highlight it and then dragging files in,
        or copy and paste any relevant log output.
        :warning: _Remember to redact or remove any sensitive information!_
    validations:
      required: false
  - type: input
    id: phpversion
    attributes:
      label: Version PHP
      description: What version of PHP are you running?
      placeholder: Enter the PHP version you are using
    validations:
      required: false
  - type: dropdown
    id: osversion
    attributes:
      label: "Operating System"
      description: What version of operating system are you running?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
      default: 1
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
