name: 🚀 Feature request
description: Suggest an idea for improving Yii
body:
  - type: textarea
    attributes:
      label: Proposed new feature or change
      description: |
        Please provide a description of the feature or enhancement.
        If the feature is UI-related, add screenshots, mockups or videos.
        If you're requesting an implementation of some standard or API, link the relevant resources.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false