
name: Report a Issues
description: Create a report to help us improve
body:
- type: markdown
  attributes:
    value: |
      > If you have encountered a SECURITY RELATED ISSUE with Yii, [use the form](https://www.yiiframework.com/security) to report any security issues you have encountered to us. ***WARNING!*** DO NOT use the issue tracker or discuss it in the public forum as this will cause more harm than help.
- type: textarea
  id: expected
  attributes:
    label: What is the expected result?
    placeholder: Describe what you expected to happen
  validations:
    required: false
- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      > **Please use the [Yii Chat channel](https://t.me/yii3en), [IRC channel](ircs://irc.libera.chat:6697/yii) or [Yii Forum](https://forum.yiiframework.com/c/yii-3-0/63) for questions.**
- type: input
  id: phpversion
  attributes:
    label: Version PHP
    description: What version of PHP are you running?
    placeholder: Enter the PHP version you are using
  validations:
    required: false
- type: dropdown
  id: osversion
  attributes:
    label: Operating System
    description: What version of operating system are you running?
    multiple: false
    options:
      - Microsoft Windows
      - Apple macOS
      - Linux
    default: 2
  validations:
    required: false
